version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb-data:/opt/couchdb/data

volumes:
  couchdb-data: